<?php

namespace App\Repository\Users\Adminuser;

use Doctrine\ORM\EntityRepository;

/**
 * ParametreadminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametreadminRepository extends EntityRepository
{
public function myFindAll()
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.user','u')
				  ->addSelect('u')
	              ->orderBy('p.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
