api_platform:
    title: 'AZ Elearning API Plateforme With Swagger V3 '
    description: "API développée dans le but de mettre en place la transition vers les l'architectures en microservices"
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header
