<?php

namespace App\Repository\Produit\Produit;

use Doctrine\ORM\EntityRepository;

/**
 * CataloguechantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CataloguechantierRepository extends EntityRepository
{
	public function myfindAll()
	{
		$query = $this->createQueryBuilder('c')
					  ->orderBy('c.rang','ASC')
					  ->getQuery();
		return $query->getResult();
	}
}
