<?php
namespace App\Repository\Produit\Produit;

use Doctrine\ORM\EntityRepository;

/**
 * ComposquestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposquestionnaireRepository extends EntityRepository
{
public function myfindComposquestionnaire($idpropan,$idchapter)
{
	$query = $this->createQueryBuilder('c')
	              ->leftJoin('c.produitpanier','p')
	              ->leftJoin('c.questionnaire','q')
	              ->leftJoin('q.chapitrecours','h')
				  ->addSelect('p')
				  ->addSelect('q')
				  ->addSelect('h')
				  ->where('p.id = :id')
				  ->andWhere('h.id = :idh')
				  ->setParameter('id',$idpropan)
				  ->setParameter('idh',$idchapter)
	              ->orderBy('c.date','DESC')
                  ->getQuery();
	return $query->getResult();
}
}
