<?php
namespace App\Repository\Produit\Produit;

use Doctrine\ORM\EntityRepository;

/**
 * CorrectionpratiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrectionpratiqueRepository extends EntityRepository
{
}
