<?php
namespace App\Repository\Produit\Produit;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends EntityRepository
{
public function getPanierScategorie($id)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.produitpaniers','r')
	              ->leftJoin('r.produit','o')
	              ->leftJoin('o.souscategorie','s')
				  ->addSelect('r')
				  ->addSelect('o')
				  ->addSelect('s')
				  ->where('s.id = :id')
				  ->andWhere('p.payer = 1')
				  ->setParameter('id',$id)
                  ->getQuery();
	return $query->getResult();
}
public function getPanierProduitUser($id)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.produitpaniers','r')
	              ->leftJoin('r.produit','o')
	              ->leftJoin('o.user','u')
				  ->addSelect('r')
				  ->addSelect('o')
				  ->addSelect('u')
				  ->where('u.id = :id')
				  ->andWhere('p.payer = 1')
				  ->setParameter('id',$id)
				  ->orderBy('p.date','DESC')
                  ->getQuery();
	return $query->getResult();
}
public function getPanierScategorieGagnant($id)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.produitpaniers','r')
	              ->leftJoin('r.produit','o')
	              ->leftJoin('o.souscategorie','s')
				  ->addSelect('r')
				  ->addSelect('o')
				  ->addSelect('s')
				  ->where('s.id = :id')
				  ->andWhere('p.payer = 1 AND p.nbgagner >= 3')
				  ->setParameter('id',$id)
	              ->orderBy('p.nbticket','DESC')
                  ->getQuery();
	return $query->getResult();
}
public function getPanierScategorieGagnantQuartre($id)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.produitpaniers','r')
	              ->leftJoin('r.produit','o')
	              ->leftJoin('o.souscategorie','s')
				  ->addSelect('r')
				  ->addSelect('o')
				  ->addSelect('s')
				  ->where('s.id = :id')
				  ->andWhere('p.payer = 1 AND p.nbgagner >= 4')
				  ->setParameter('id',$id)
	              ->orderBy('p.nbticket','DESC')
                  ->getQuery();
	return $query->getResult();
}
public function getPanierScategorieGagnantCinq($id)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.produitpaniers','r')
	              ->leftJoin('r.produit','o')
	              ->leftJoin('o.souscategorie','s')
				  ->addSelect('r')
				  ->addSelect('o')
				  ->addSelect('s')
				  ->where('s.id = :id')
				  ->andWhere('p.payer = 1 AND p.nbgagner >= 5')
				  ->setParameter('id',$id)
	              ->orderBy('p.nbticket','DESC')
                  ->getQuery();
	return $query->getResult();
}
public function getPanierTroisGagnant($id)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.produitpaniers','r')
	              ->leftJoin('r.produit','o')
	              ->leftJoin('o.souscategorie','s')
				  ->addSelect('r')
				  ->addSelect('o')
				  ->addSelect('s')
				  ->where('s.id = :id')
				  ->andWhere('p.payer = 1 AND p.nbgagner = 3')
				  ->setParameter('id',$id)
	              ->orderBy('p.nbticket','DESC')
                  ->getQuery();
	return $query->getResult();
}
public function getPanierQuartreGagnant($id)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.produitpaniers','r')
	              ->leftJoin('r.produit','o')
	              ->leftJoin('o.souscategorie','s')
				  ->addSelect('r')
				  ->addSelect('o')
				  ->addSelect('s')
				  ->where('s.id = :id')
				  ->andWhere('p.payer = 1 AND p.nbgagner = 4')
				  ->setParameter('id',$id)
	              ->orderBy('p.nbticket','DESC')
                  ->getQuery();
	return $query->getResult();
}
public function getPanierCinqGagnant($id)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.produitpaniers','r')
	              ->leftJoin('r.produit','o')
	              ->leftJoin('o.souscategorie','s')
				  ->addSelect('r')
				  ->addSelect('o')
				  ->addSelect('s')
				  ->where('s.id = :id')
				  ->andWhere('p.payer = 1 AND p.nbgagner = 5')
				  ->setParameter('id',$id)
	              ->orderBy('p.nbticket','DESC')
                  ->getQuery();
	return $query->getResult();
}

public function listepanierinvalide($page, $nombreParPage)
{
	if($page < 1){
		throw new \InvalidArgumentException('Page inexistant');
		}
		$query = $this->createQueryBuilder('p')
					  ->leftJoin('p.user', 'u')
					  ->addSelect('u')
					  ->where('p.valide = 1')
					  ->andWhere('p.livrer = 0')
					  ->orderBy('p.date','DESC')
					  ->getQuery();
		// On définit l'établissemnt à partir duquel commencer la liste
		$query->setFirstResult(($page-1) * $nombreParPage)
		// Ainsi que le nombre d'établissement à afficher
			  ->setMaxResults($nombreParPage);
		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
	return new Paginator($query);
}
}
