<?php
namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;

/**
 * AproposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AproposRepository extends EntityRepository
{
public function myfindAll()
{
	$query = $this->createQueryBuilder('a')
	              ->orderBy('a.rang','DESC')
                  ->getQuery();
	return $query->getResult();
}
}
