#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_directory_general:
    resource: '../src/Routing/General/'
    type: directory
app_directory_produit:
    resource: '../src/Routing/Produit/'
    type: directory
app_directory_users:
    resource: '../src/Routing/Users/'
    type: directory
app_directory_offre:
    resource: '../src/Routing/Pricing/'
    type: directory
login:
    path: /login/{id}/{position}
    controller: App\Controller\Users\User\SecurityController::login
    defaults:
        id: 0
        position: "ads"
    requirements:
        id: \d+