<?php
namespace App\Repository\Users\User;

use Doctrine\ORM\EntityRepository;

/**
 * ImgslideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgslideRepository extends EntityRepository
{
public function findSlideAccueil()
{
	$query = $this->createQueryBuilder('i')
				  ->where('i.acceuil = 1')
	              ->orderBy('i.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function findSlideConnexion()
{
	$query = $this->createQueryBuilder('i')
				  ->where('i.annonce = 1')
	              ->orderBy('i.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function findSlideAnnonce()
{
	$query = $this->createQueryBuilder('i')
				  ->where('i.annonce = 0 AND i.acceuil = 0')
	              ->orderBy('i.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
