<?php
namespace App\Repository\Users\User;

use Doctrine\ORM\EntityRepository;

/**
 * SujetepingleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetepingleRepository extends EntityRepository
{
}
