<?php
namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * InfoentrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoentrepriseRepository extends EntityRepository
{
public function myFindAll()
{
	$query = $this->createQueryBuilder('i')
	              ->leftJoin('i.detailinfoentreprises','d')
	              ->leftJoin('i.imginfoentreprise','ig')
				  ->addSelect('d')
				  ->addSelect('ig')
	              ->orderBy('i.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function listeAllArticleEntreprise($page,$nombreParPage)
{
	 // On déplace la vérification du numéro de page dans cette méthode
    if ($page < 1) {
    throw new \InvalidArgumentException('Page inexistant');
     }
    // La construction de la requête reste inchangée
    $query = $this->createQueryBuilder('i')
	              ->leftJoin('i.detailinfoentreprises', 'd')
				  ->addSelect('d')
                  ->orderBy('i.rang', 'DESC')
                  ->getQuery();
    // On définit l'établissemnt à partir duquel commencer la liste
    $query->setFirstResult(($page-1) * $nombreParPage)
    // Ainsi que le nombre d'établissement à afficher
          ->setMaxResults($nombreParPage);
    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
return new Paginator($query);
}
}
