<?php
namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends EntityRepository
{
public function findInterventionSujet($id,$page,$nombreParPage)
{
	// On déplace la vérification du numéro de page dans cette méthode
    if ($page < 1) {
    throw new \InvalidArgumentException('Page inexistant');
     }
    // La construction de la requête reste inchangée
    $query = $this->createQueryBuilder('i')
	              ->leftJoin('i.commentaireblog', 'c')
				  ->addSelect('c')
				  ->where('c.id = :id')
				  ->setParameter('id', $id)
                  ->orderBy('i.date', 'ASC')
                  ->getQuery();
    // On définit l'établissemnt à partir duquel commencer la liste
    $query->setFirstResult(($page-1) * $nombreParPage)
    // Ainsi que le nombre d'établissement à afficher
          ->setMaxResults($nombreParPage);
    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
return new Paginator($query);
}
}
