<?php
namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
public function myfindAll()
{
	$query = $this->createQueryBuilder('m')
	              ->orderBy('m.date','DESC')
                  ->getQuery();
	return $query->getResult();
}
}
