<?php
namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;

/**
 * MessemailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessemailRepository extends EntityRepository
{
}
